# Generated by Django 3.1.5 on 2021-01-30 17:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('capture_rate', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('flavor_text', models.TextField()),
                ('height', models.IntegerField()),
                ('moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('name', models.CharField(max_length=100)),
                ('sprites', models.JSONField()),
                ('stats', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonsOwn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('is_party_menber', models.BooleanField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemons')),
            ],
        ),
    ]
