# Generated by Django 3.1.5 on 2021-01-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonsown',
            name='specie',
        ),
        migrations.AddField(
            model_name='pokemonsown',
            name='specie',
            field=models.ManyToManyField(to='pokemons.Pokemons'),
        ),
    ]
