# Generated by Django 3.1.5 on 2021-01-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_auto_20210130_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonsown',
            name='specie',
        ),
        migrations.AddField(
            model_name='pokemonsown',
            name='specie',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemons'),
        ),
    ]
