# Generated by Django 3.1.5 on 2021-01-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_auto_20210130_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemons',
            options={'verbose_name_plural': 'pokemons'},
        ),
        migrations.AlterField(
            model_name='pokemonsown',
            name='specie',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemons', verbose_name='pokemons'),
        ),
    ]
