# Generated by Django 3.1.5 on 2021-01-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_auto_20210130_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonsown',
            name='specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemons', verbose_name='pokemons'),
        ),
    ]
